# Generated by Django 4.2 on 2023-10-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApi', '0001_initial'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='CoursesApi.course'),
        ),
    ]
